export interface WordPrompt {
  word: string
  prompt: string // short visual context only — GLOBAL_PROMPT_PREFIX is prepended at request time
}

export const GLOBAL_PROMPT_PREFIX = 'Vibrant colorful illustration, use the sketch as a rough guide: '

export const WORD_PROMPTS: WordPrompt[] = [
  { word: 'Volcano',        prompt: 'volcano, mountain, eruption, triangle, cone shape' },
  { word: 'Rollercoaster',  prompt: 'rollercoaster, theme park ride, tracks, looping lines, wavy curves' },
  { word: 'Hot Air Balloon', prompt: 'hot air balloon, blimp, teardrop shape, circle, square basket' },
  { word: 'Submarine',      prompt: 'submarine, underwater boat, long oval, cylinder, pill shape' },
  { word: 'T-Rex',          prompt: 't-rex, dinosaur, trex, big lizard, heavy blocky shapes' },
  { word: 'Castle',         prompt: 'castle, fortress, tower, squares, rectangles, triangle roof' },
  { word: 'Spaceship',      prompt: 'spaceship, rocket, ufo, triangle, dart shape, oval' },
  { word: 'Staircase',      prompt: 'staircase, stairs, steps, zigzag lines, ascending blocks' },
  { word: 'Tornado',        prompt: 'tornado, twister, cyclone, spiral, spinning cone' },
  { word: 'Pirate Ship',    prompt: 'pirate ship, galleon, boat, half circle, triangle sails' },
  { word: 'Haunted House',  prompt: 'haunted house, creepy mansion, square building, triangle roof, crooked lines' },
  { word: 'Robot',          prompt: 'robot, android, cyborg, square head, rectangle body, blocky shapes' },
  { word: 'Pizza',          prompt: 'pizza, pizza slice, flat circle, triangle wedge, round pepperonis' },
  { word: 'Guitar',         prompt: 'guitar, acoustic guitar, figure eight shape, long rectangle neck, straight lines' },
  { word: 'Lighthouse',     prompt: 'lighthouse, beacon tower, tall cylinder, rectangle, triangle top' },
  { word: 'Drone',          prompt: 'drone, quadcopter, flat square, four small circles, cross shape' },
  { word: 'Umbrella',       prompt: 'umbrella, parasol, half circle, dome, straight vertical line handle' },
  { word: 'Train',          prompt: 'train, locomotive, railway car, long rectangles, connecting blocks, circles for wheels' },
  { word: 'Camera',         prompt: 'camera, photograph machine, square body, large circle lens, rectangle' },
  { word: 'Helicopter',     prompt: 'helicopter, chopper, round teardrop body, long straight line tail, crossing lines for blades' },
  { word: 'Waterfall',      prompt: 'waterfall, river cascade, vertical lines, steep drop' },
  { word: 'Forest',         prompt: 'forest, woods, trees, tall vertical lines, bumpy circles, triangles' },
  { word: 'Desert',         prompt: 'desert, sahara, dunes, wavy horizontal lines, rolling curves' },
  { word: 'Glacier',        prompt: 'glacier, iceberg, frozen mountain, jagged triangles, sharp blocky shapes' },
  { word: 'Coral Reef',     prompt: 'coral reef, underwater plants, bumpy circles, squiggly lines' },
  { word: 'Meteor',         prompt: 'meteor, shooting star, asteroid, round rock, diagonal trailing lines' },
  { word: 'Cave',           prompt: 'cave, cavern, tunnel, dark half circle, arched doorway shape' },
  { word: 'Beach',          prompt: 'beach, seashore, coast, curving horizontal lines, flat landscape' },
  { word: 'Time Machine',   prompt: 'time machine, sci-fi pod, round sphere, boxes, spinning circles' },
  { word: 'Telescope',      prompt: 'telescope, spyglass, long diagonal cylinder, overlapping tubes, triangle stand' },
  { word: 'Cyberpunk',      prompt: 'cyberpunk city, futuristic street, tall glowing rectangles, straight vertical lines' },
  { word: 'Satellite',      prompt: 'satellite, space probe, flat rectangles, central cylinder, crossing geometric shapes' },
  { word: 'Jetpack',        prompt: 'jetpack, rocket pack, two vertical cylinders, rectangles, straight lines downward' },
  { word: 'Arcade Game',    prompt: 'arcade game, retro cabinet, tall rectangle box, square screen' },
  { word: 'Laser',          prompt: 'laser, beam of light, straight diagonal line, sharp rigid line' },
  { word: 'Dragon',         prompt: 'dragon, mythical beast, winged lizard, sharp triangles, curvy serpentine lines' },
  { word: 'Sword',          prompt: 'sword, blade, long skinny rectangle, cross shape, pointed triangle tip' },
  { word: 'Magic Wand',     prompt: 'magic wand, wizard staff, long thin straight line, star shape, circles' },
  { word: 'Mummy',          prompt: 'mummy, pharaoh, cylinder shape, horizontal wrapping lines, humanoid shape' },
  { word: 'Treasure',       prompt: 'treasure, chest, open rectangle box, half circle lid, shiny circles' },
  { word: 'Knight',         prompt: 'knight, armor, warrior, rectangle body, cylinder limbs, stiff geometric shapes' },
  { word: 'Pegasus',        prompt: 'pegasus, flying horse, oval body, long curves, wide triangle wings' },
  { word: 'Bridge',         prompt: 'bridge, overpass, long horizontal rectangle, vertical supporting lines, arches' },
  { word: 'Skyscraper',     prompt: 'skyscraper, highrise building, very tall rectangle, grid of small squares, vertical lines' },
  { word: 'Tractor',        prompt: 'tractor, farm vehicle, blocky squares, two giant circles, two small circles' },
  { word: 'Ferris Wheel',   prompt: 'ferris wheel, big wheel, giant circle, crossing straight lines, small hanging squares' },
  { word: 'Hamburger',      prompt: 'hamburger, cheeseburger, flat ovals, stacked horizontal layers, half circle top' },
  { word: 'Sneaker',        prompt: 'sneaker, running shoe, curved L-shape, flat bottom line, triangle wedge' },
  { word: 'Ice Cream',      prompt: 'ice cream, cone, upside down triangle, stacked circles, swirling round top' },
  { word: 'Backpack',       prompt: 'backpack, rucksack, big square, half circle top, small rectangle pocket' },

  // --- Everyday Objects ---
  { word: 'Kettle',         prompt: 'kettle, teapot, jug, rounded pot body, curved spout, loop handle' },
  { word: 'Toaster',        prompt: 'toaster, bread machine, wide rectangle box, two narrow slots on top' },
  { word: 'Microphone',     prompt: 'microphone, mic, rounded oval ball top, long thin cylinder handle' },
  { word: 'Glasses',        prompt: 'glasses, spectacles, two ovals side by side, bridge piece connecting, eyeframes' },
  { word: 'Fork',           prompt: 'fork, cutlery, long thin handle, three pointed prong tips at top' },
  { word: 'Key',            prompt: 'key, lock opener, oval head with hole, rectangular handle, notched teeth edge' },
  { word: 'Ladder',         prompt: 'ladder, climbing, two parallel vertical lines, many horizontal rungs between' },
  { word: 'Bucket',         prompt: 'bucket, pail, cylinder wider at top than bottom, curved arc handle' },
  { word: 'Scissors',       prompt: 'scissors, cutting tool, X cross shape, oval loop handles, two crossing blades' },
  { word: 'Candle',         prompt: 'candle, wax stick, tall thin cylinder, small teardrop flame at top' },
  { word: 'Briefcase',      prompt: 'briefcase, work bag, flat rectangle, handle on top, clasp in middle' },
  { word: 'Watering Can',   prompt: 'watering can, garden jug, oval body, long angled spout, loop handle' },
  { word: 'Mug',            prompt: 'mug, coffee cup, cylinder, curved D-shaped handle attached on side' },
  { word: 'Hourglass',      prompt: 'hourglass, sand timer, two triangle cones point to point, narrow pinch waist, sand' },
  { word: 'Compass',        prompt: 'compass, navigation tool, circular dial face, rotating arrow needle, N S E W marks' },
  { word: 'Shield',         prompt: 'shield, knight armor, tall curved rectangle, pointed bottom, crest marking' },
  { word: 'Binoculars',     prompt: 'binoculars, two joined cylinder tubes, oval lenses, viewing device, side by side' },
  { word: 'Magnifying Glass', prompt: 'magnifying glass, round circle lens, short handle stick, detective tool' },

  // --- Animals ---
  { word: 'Flamingo',       prompt: 'flamingo, wading bird, S-curve long neck, long thin stick legs, teardrop body' },
  { word: 'Elephant',       prompt: 'elephant, large mammal, big oval body, long curving trunk, large round ears' },
  { word: 'Penguin',        prompt: 'penguin, arctic bird, rounded oval body, small flippers, black and white' },
  { word: 'Octopus',        prompt: 'octopus, sea creature, round dome head, eight curling wavy tentacles' },
  { word: 'Snail',          prompt: 'snail, shell creature, tight spiral shell, small oval body, two antenna sticks' },
  { word: 'Butterfly',      prompt: 'butterfly, insect, two large symmetric wing shapes, oval body, thin antennae' },
  { word: 'Crab',           prompt: 'crab, crustacean, wide flat oval body, two large pincer claws, short legs' },
  { word: 'Parrot',         prompt: 'parrot, tropical bird, hooked beak curve, round body, long pointed tail feathers' },
  { word: 'Whale',          prompt: 'whale, sea mammal, large elongated oval body, wide flat tail fin, water spout' },
  { word: 'Peacock',        prompt: 'peacock, bird, large fan tail spread wide, circular eye spots on feathers' },

  // --- Movie Titles ---
  { word: 'Titanic',        prompt: 'ocean liner, massive ship, long rectangle hull, smokestacks, iceberg' },
  { word: 'Jaws',           prompt: 'great white shark, large triangle fin, wide open jaws with teeth, ocean wave' },
  { word: 'The Lion King',  prompt: 'lion with large mane, pride rock cliff silhouette, sun circle, savanna' },
  { word: 'Frozen',         prompt: 'ice palace, spiky frozen towers, snowflake crystal, snowy mountain' },
  { word: 'Up',             prompt: 'house floating lifted by hundreds of round balloons, ropes, colorful circles' },
  { word: 'Shrek',          prompt: 'green ogre face, round wide head, droopy ears, large nose, swamp' },
  { word: 'Toy Story',      prompt: 'cowboy toy doll, astronaut space suit figure, toy box, bedroom floor' },
  { word: 'Finding Nemo',   prompt: 'clownfish, orange white stripe fish, coral reef, underwater bubbles' },
  { word: 'Jurassic Park',  prompt: 't-rex dinosaur, jungle, electric fence, jeep, tropical leaves' },
  { word: 'Inception',      prompt: 'city street folding upward, tilted buildings, spinning top, dream layers' },
  { word: 'The Matrix',     prompt: 'green code raining down, man in black trench coat and sunglasses, dark city' },
  { word: 'Alien',          prompt: 'elongated alien skull, tall oval head, dark corridor, egg shape, creature' },
  { word: 'Home Alone',     prompt: 'boy with hands on cheeks screaming, house in snow, christmas, surprised face' },
  { word: 'Grease',         prompt: '1950s car, leather jacket figure, slicked pompadour hair, drive-in screen' },
  { word: 'Interstellar',   prompt: 'black hole ring, circular glowing wormhole, space, spacecraft, orbit' },

  // --- Famous People / Characters ---
  { word: 'Einstein',       prompt: 'wild spiky white hair, scientist, chalkboard equations, small mustache' },
  { word: 'Elvis',          prompt: 'quiff pompadour hair, guitar, jewelled jumpsuit, microphone, stage performer' },
  { word: 'Cleopatra',      prompt: 'Egyptian headdress, heavy eye makeup, ornate collar necklace, throne, queen' },
  { word: 'Napoleon',       prompt: 'bicorne two-pointed hat, military uniform, hand tucked in jacket, short figure' },
  { word: 'Charlie Chaplin', prompt: 'round bowler hat, thin walking cane, small toothbrush mustache, baggy suit' },
  { word: 'Santa Claus',    prompt: 'red round suit, large white beard, sack of gifts, jolly round belly, hat' },
  { word: 'Darth Vader',    prompt: 'black rounded dome helmet, black flowing cape, lightsaber, chest panel' },
  { word: 'Harry Potter',   prompt: 'round circle glasses, lightning bolt scar on forehead, wand stick, wizard robe' },
  { word: 'Sherlock Holmes', prompt: 'deerstalker cap hat, curved pipe, magnifying glass, long cape coat, detective' },
  { word: 'Mona Lisa',      prompt: 'woman portrait, slight smile, dark hair, hands folded, landscape behind, frame' },

  // --- Phrases / Idioms ---
  { word: 'Fish Out of Water',     prompt: 'fish on dry land, flopping, distressed fish outside bowl, gasping' },
  { word: 'Raining Cats and Dogs', prompt: 'cats and dogs falling from storm clouds, heavy rain, animals dropping down' },
  { word: 'Elephant in the Room',  prompt: 'large elephant standing inside small room, furniture squeezed around it' },
  { word: 'Bite the Bullet',       prompt: 'person biting a bullet in teeth, grimacing, enduring pain, determined' },
  { word: 'Piece of Cake',         prompt: 'single slice of cake on plate, simple, easy, fork beside it' },
  { word: 'Walking on Thin Ice',   prompt: 'person stepping on cracked ice sheet, zigzag cracks spreading, frozen lake' },
  { word: 'Burning Bridges',       prompt: 'bridge on fire, flames and smoke rising, burning arch over water' },
  { word: 'Storm in a Teacup',     prompt: 'tiny storm swirling inside large teacup, miniature lightning, saucer' },
  { word: 'Hit the Road',          prompt: 'person with suitcase walking away on road, waving goodbye, leaving' },
  { word: 'Let the Cat Out of the Bag', prompt: 'cat leaping out of open sack bag, surprised person, escape' },
  { word: 'Break a Leg',           prompt: 'leg bone in plaster cast, crutches, broken limb, theatre curtain' },
  { word: 'Kick the Bucket',       prompt: 'foot kicking a metal bucket sideways, liquid spilling, scattering' },

  // --- Nature / Places ---
  { word: 'Rainbow',        prompt: 'rainbow, arc of curved color stripes, clouds on each end, semicircle arch' },
  { word: 'Northern Lights', prompt: 'aurora borealis, wavy curtain bands of light, dark night sky, vertical waves' },
  { word: 'Tidal Wave',     prompt: 'tsunami, giant curling wave, towering wall of water, curved crest above boat' },
  { word: 'Geyser',         prompt: 'geyser, hot spring, tall vertical water jet column, steam cloud, rocks' },
  { word: 'Cliff',          prompt: 'cliff edge, steep sheer vertical rock face, tall drop, sea or river below' },
  { word: 'Avalanche',      prompt: 'avalanche, snow rushing fast down mountain slope, diagonal white cascade' },
  { word: 'Lagoon',         prompt: 'tropical lagoon, blue enclosed pool, oval land surrounding, palm trees' },
  { word: 'Quicksand',      prompt: 'quicksand, sandy sinking pit, person sinking, arms reaching up, trapped' },

  // --- Sports / Activities ---
  { word: 'Surfing',        prompt: 'surfer, person standing on surfboard, large curved wave, balancing upright' },
  { word: 'Archery',        prompt: 'archery, bow and arrow, circular target with rings, bullseye, aiming' },
  { word: 'Boxing',         prompt: 'boxing ring, two fighters with large round gloves, rope square ring, corner posts' },
  { word: 'Tightrope',      prompt: 'tightrope walker, long thin horizontal rope, balance pole held out, high wire' },
  { word: 'Juggling',       prompt: 'juggler, multiple balls in arc above, circus performer, round shapes flying' },
  { word: 'Skydiving',      prompt: 'skydiver, person falling with arms spread, parachute dome canopy above, clouds' },
  { word: 'Ice Skating',    prompt: 'ice skater, person spinning on ice, blades on feet, oval rink, graceful spin' },
  { word: 'Bowling',        prompt: 'bowling lane rectangle alley, ball rolling toward triangle of pins at far end' },
  { word: 'Gymnastics',     prompt: 'gymnast, flexible person, ribbon swirl arc, curved bending body, splits' },
  { word: 'Pole Vault',     prompt: 'pole vault, athlete with long bendy pole, high bar above, arcing jump over' },

  // --- Food & Drink ---
  { word: 'Sushi',          prompt: 'sushi roll, circular cross-section slice, seaweed wrap, rice oval, chopsticks' },
  { word: 'Taco',           prompt: 'taco, folded curved shell, U-shape, fillings visible, crunchy half-moon' },
  { word: 'Pancakes',       prompt: 'stack of pancakes, flat circles piled high, syrup dripping down sides' },
  { word: 'Spaghetti',      prompt: 'spaghetti, bowl of pasta, swirling tangled noodles, circular bowl, meatball' },
  { word: 'Pineapple',      prompt: 'pineapple, oval fruit, crown of spiky leaves, diamond cross-hatch pattern skin' },
  { word: 'Watermelon',     prompt: 'watermelon, large round oval, green stripe skin, red inside half slice' },
  { word: 'Donut',          prompt: 'donut, ring torus shape, circular with center hole, frosting glaze drizzle' },
  { word: 'Birthday Cake',  prompt: 'birthday cake, round layered cylinder, candles on top, frosting sides, tiered' },
  { word: 'Hot Dog',        prompt: 'hot dog, sausage in oblong bun, cylinder meat in oval bread, condiment lines' },
  { word: 'Pretzel',        prompt: 'pretzel, knotted bread, looped figure-eight knot twist shape, twisted overlap' },

  // --- Fun Misc ---
  { word: 'Sombrero',       prompt: 'sombrero, wide brim hat, very large flat circle brim, tall rounded crown' },
  { word: 'Igloo',          prompt: 'igloo, ice dome house, white hemisphere, snow block bricks, arched entrance' },
  { word: 'Windmill',       prompt: 'windmill, tall tower, four long X-cross blades, spinning fan arms extended' },
  { word: 'Cotton Candy',   prompt: 'cotton candy, fluffy large cloud on stick, oval soft puff, carnival, pink swirl' },
  { word: 'Sandcastle',     prompt: 'sandcastle, beach fort, cone tower turrets, rectangular walls, moat around' },
  { word: 'Treehouse',      prompt: 'treehouse, wooden house platform in tree, rope ladder, tree trunk and branches' },
  { word: 'Hammock',        prompt: 'hammock, hanging bed, diagonal sagging netting, between two tree trunks' },
  { word: 'Skateboard',     prompt: 'skateboard, flat long rectangle board, four small circle wheels underneath' },
  { word: 'Swing',          prompt: 'playground swing, two vertical chains, horizontal bar at top, seat at bottom' },
  { word: 'Tent',           prompt: 'tent, camping shelter, A-frame triangle shape, two slanted sides meeting at peak' },
  { word: 'Sundial',        prompt: 'sundial, circular stone plate, triangular gnomon pointer, time marks around' },
  { word: 'Periscope',      prompt: 'periscope, submarine viewer, L-shaped angled tube, mirror inside, rectangular' },
  { word: 'Weather Vane',   prompt: 'weather vane, directional arrow, N S E W arms, rooster or arrow on spike top' },
]

export function pickRandom(exclude?: WordPrompt): WordPrompt {
  const pool = exclude ? WORD_PROMPTS.filter((w) => w.word !== exclude.word) : WORD_PROMPTS
  return pool[Math.floor(Math.random() * pool.length)]
}
